spring:       ########MY SQL##################
  datasource:
    url: jdbc:mysql://localhost:3306/testdtbase?useSSL=false
    username: root
    password: root
  jpa:        ########HIBERNATE###############
    show-sql: true
    hibernate:
      ddl-auto: create #Si actualiza un campo de la entity elimina el campo de la tabla de la bbdd
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy  #Forma dialecto al hacer las consultas
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #Para respetar mayusculas y minusculas sin guiones
    properties:
      hibernate:  
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect  #Dialecto de la bbdd --cambiado a InnoDB
  thymeleaf:
    cache: false
